version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=${PUSER}
      - POSTGRES_PASSWORD=${PPASSWORD}
      - POSTGRES_DB=${PDB}
      - POSTGRES_HOST_AUTH_METHOD="trust"
    volumes:
      - ./trackdata.sql:/docker-entrypoint-initdb.d/trackdata.sql
    ports:
      - '5432:5432'

  trends:
    container_name: trends_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '443:443'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/${PDB}
      - SPRING_DATASOURCE_USERNAME=${PUSER}
      - SPRING_DATASOURCE_PASSWORD=${PPASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - psql-db

